

function(tinyvk_set_msvc_runtime_lib TARGET)
    if (WIN32)
        set(LIB_NAME "MultiThreaded$<$<CONFIG:Debug>:Debug>")
        if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
            set(LIB_NAME ${LIB_NAME}DLL)
        endif()
        set_property(TARGET ${TARGET} PROPERTY MSVC_RUNTIME_LIBRARY ${LIB_NAME})
    endif()
endfunction()


function(tinyvk_link_shaderc TARGET)
    if (WIN32)
        set(SHADERC_NAME "shaderc_combined")
        if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
            set(SHADERC_NAME ${SHADERC_NAME}d)
        endif()
        set(SHADERC_LIB_PATH "$ENV{VULKAN_SDK}/lib/${SHADERC_NAME}.lib")
        if (NOT EXISTS "${SHADERC_LIB_PATH}")
            message(FATAL_ERROR "Cannot find ${SHADERC_NAME}.lib to link, did you set the VULKAN_SDK environment variable?")
        endif()
        target_link_libraries(${TARGET} PRIVATE "${SHADERC_LIB_PATH}")
        tinyvk_set_msvc_runtime_lib(${TARGET})
    else()
        if (NOT EXISTS "$ENV{VULKAN_SDK}/lib/libshaderc_combined.a")
            message(FATAL_ERROR "Cannot find libshaderc_combined.a to link, did you set the VULKAN_SDK environment variable?")
        endif()
        target_link_libraries(${TARGET} PRIVATE pthread $ENV{VULKAN_SDK}/lib/libshaderc_combined.a)
    endif()
    file(TO_CMAKE_PATH "$ENV{VULKAN_SDK}" VSDK)
    target_compile_definitions(${TARGET} PRIVATE VULKAN_SDK_PATH="${VSDK}")
endfunction()
